/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-30 at 14:27:26 UTC 
 * Modify at your own risk.
 */

package de.yourtasks.taskendpoint.model;

/**
 * Model definition for Task.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the taskendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Task extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime completed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long parentTaskId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer prio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer repeatIntervalDays;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCompleted() {
    return completed;
  }

  /**
   * @param completed completed or {@code null} for none
   */
  public Task setCompleted(com.google.api.client.util.DateTime completed) {
    this.completed = completed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public Task setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Task setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Task setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getParentTaskId() {
    return parentTaskId;
  }

  /**
   * @param parentTaskId parentTaskId or {@code null} for none
   */
  public Task setParentTaskId(java.lang.Long parentTaskId) {
    this.parentTaskId = parentTaskId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPrio() {
    return prio;
  }

  /**
   * @param prio prio or {@code null} for none
   */
  public Task setPrio(java.lang.Integer prio) {
    this.prio = prio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRepeatIntervalDays() {
    return repeatIntervalDays;
  }

  /**
   * @param repeatIntervalDays repeatIntervalDays or {@code null} for none
   */
  public Task setRepeatIntervalDays(java.lang.Integer repeatIntervalDays) {
    this.repeatIntervalDays = repeatIntervalDays;
    return this;
  }

  @Override
  public Task set(String fieldName, Object value) {
    return (Task) super.set(fieldName, value);
  }

  @Override
  public Task clone() {
    return (Task) super.clone();
  }

}
