/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-26 at 20:36:54 UTC 
 * Modify at your own risk.
 */

package de.yourtasks.projectendpoint;

/**
 * Service definition for Projectendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ProjectendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Projectendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the projectendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://esoteric-pen-466.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "projectendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Projectendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Projectendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getProject".
   *
   * This request holds the parameters needed by the the projectendpoint server.  After setting any
   * optional parameters, call the {@link GetProject#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetProject getProject(java.lang.Long id) throws java.io.IOException {
    GetProject result = new GetProject(id);
    initialize(result);
    return result;
  }

  public class GetProject extends ProjectendpointRequest<de.yourtasks.projectendpoint.model.Project> {

    private static final String REST_PATH = "project/{id}";

    /**
     * Create a request for the method "getProject".
     *
     * This request holds the parameters needed by the the projectendpoint server.  After setting any
     * optional parameters, call the {@link GetProject#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetProject#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetProject(java.lang.Long id) {
      super(Projectendpoint.this, "GET", REST_PATH, null, de.yourtasks.projectendpoint.model.Project.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetProject setAlt(java.lang.String alt) {
      return (GetProject) super.setAlt(alt);
    }

    @Override
    public GetProject setFields(java.lang.String fields) {
      return (GetProject) super.setFields(fields);
    }

    @Override
    public GetProject setKey(java.lang.String key) {
      return (GetProject) super.setKey(key);
    }

    @Override
    public GetProject setOauthToken(java.lang.String oauthToken) {
      return (GetProject) super.setOauthToken(oauthToken);
    }

    @Override
    public GetProject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetProject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetProject setQuotaUser(java.lang.String quotaUser) {
      return (GetProject) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetProject setUserIp(java.lang.String userIp) {
      return (GetProject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetProject setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetProject set(String parameterName, Object value) {
      return (GetProject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertProject".
   *
   * This request holds the parameters needed by the the projectendpoint server.  After setting any
   * optional parameters, call the {@link InsertProject#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link de.yourtasks.projectendpoint.model.Project}
   * @return the request
   */
  public InsertProject insertProject(de.yourtasks.projectendpoint.model.Project content) throws java.io.IOException {
    InsertProject result = new InsertProject(content);
    initialize(result);
    return result;
  }

  public class InsertProject extends ProjectendpointRequest<de.yourtasks.projectendpoint.model.Project> {

    private static final String REST_PATH = "project";

    /**
     * Create a request for the method "insertProject".
     *
     * This request holds the parameters needed by the the projectendpoint server.  After setting any
     * optional parameters, call the {@link InsertProject#execute()} method to invoke the remote
     * operation. <p> {@link InsertProject#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link de.yourtasks.projectendpoint.model.Project}
     * @since 1.13
     */
    protected InsertProject(de.yourtasks.projectendpoint.model.Project content) {
      super(Projectendpoint.this, "POST", REST_PATH, content, de.yourtasks.projectendpoint.model.Project.class);
    }

    @Override
    public InsertProject setAlt(java.lang.String alt) {
      return (InsertProject) super.setAlt(alt);
    }

    @Override
    public InsertProject setFields(java.lang.String fields) {
      return (InsertProject) super.setFields(fields);
    }

    @Override
    public InsertProject setKey(java.lang.String key) {
      return (InsertProject) super.setKey(key);
    }

    @Override
    public InsertProject setOauthToken(java.lang.String oauthToken) {
      return (InsertProject) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertProject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertProject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertProject setQuotaUser(java.lang.String quotaUser) {
      return (InsertProject) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertProject setUserIp(java.lang.String userIp) {
      return (InsertProject) super.setUserIp(userIp);
    }

    @Override
    public InsertProject set(String parameterName, Object value) {
      return (InsertProject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listProject".
   *
   * This request holds the parameters needed by the the projectendpoint server.  After setting any
   * optional parameters, call the {@link ListProject#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListProject listProject() throws java.io.IOException {
    ListProject result = new ListProject();
    initialize(result);
    return result;
  }

  public class ListProject extends ProjectendpointRequest<de.yourtasks.projectendpoint.model.CollectionResponseProject> {

    private static final String REST_PATH = "project";

    /**
     * Create a request for the method "listProject".
     *
     * This request holds the parameters needed by the the projectendpoint server.  After setting any
     * optional parameters, call the {@link ListProject#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListProject#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListProject() {
      super(Projectendpoint.this, "GET", REST_PATH, null, de.yourtasks.projectendpoint.model.CollectionResponseProject.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListProject setAlt(java.lang.String alt) {
      return (ListProject) super.setAlt(alt);
    }

    @Override
    public ListProject setFields(java.lang.String fields) {
      return (ListProject) super.setFields(fields);
    }

    @Override
    public ListProject setKey(java.lang.String key) {
      return (ListProject) super.setKey(key);
    }

    @Override
    public ListProject setOauthToken(java.lang.String oauthToken) {
      return (ListProject) super.setOauthToken(oauthToken);
    }

    @Override
    public ListProject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListProject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListProject setQuotaUser(java.lang.String quotaUser) {
      return (ListProject) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListProject setUserIp(java.lang.String userIp) {
      return (ListProject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListProject setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListProject setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListProject set(String parameterName, Object value) {
      return (ListProject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeProject".
   *
   * This request holds the parameters needed by the the projectendpoint server.  After setting any
   * optional parameters, call the {@link RemoveProject#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveProject removeProject(java.lang.Long id) throws java.io.IOException {
    RemoveProject result = new RemoveProject(id);
    initialize(result);
    return result;
  }

  public class RemoveProject extends ProjectendpointRequest<Void> {

    private static final String REST_PATH = "project/{id}";

    /**
     * Create a request for the method "removeProject".
     *
     * This request holds the parameters needed by the the projectendpoint server.  After setting any
     * optional parameters, call the {@link RemoveProject#execute()} method to invoke the remote
     * operation. <p> {@link RemoveProject#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveProject(java.lang.Long id) {
      super(Projectendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveProject setAlt(java.lang.String alt) {
      return (RemoveProject) super.setAlt(alt);
    }

    @Override
    public RemoveProject setFields(java.lang.String fields) {
      return (RemoveProject) super.setFields(fields);
    }

    @Override
    public RemoveProject setKey(java.lang.String key) {
      return (RemoveProject) super.setKey(key);
    }

    @Override
    public RemoveProject setOauthToken(java.lang.String oauthToken) {
      return (RemoveProject) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveProject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveProject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveProject setQuotaUser(java.lang.String quotaUser) {
      return (RemoveProject) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveProject setUserIp(java.lang.String userIp) {
      return (RemoveProject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveProject setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveProject set(String parameterName, Object value) {
      return (RemoveProject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateProject".
   *
   * This request holds the parameters needed by the the projectendpoint server.  After setting any
   * optional parameters, call the {@link UpdateProject#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link de.yourtasks.projectendpoint.model.Project}
   * @return the request
   */
  public UpdateProject updateProject(de.yourtasks.projectendpoint.model.Project content) throws java.io.IOException {
    UpdateProject result = new UpdateProject(content);
    initialize(result);
    return result;
  }

  public class UpdateProject extends ProjectendpointRequest<de.yourtasks.projectendpoint.model.Project> {

    private static final String REST_PATH = "project";

    /**
     * Create a request for the method "updateProject".
     *
     * This request holds the parameters needed by the the projectendpoint server.  After setting any
     * optional parameters, call the {@link UpdateProject#execute()} method to invoke the remote
     * operation. <p> {@link UpdateProject#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link de.yourtasks.projectendpoint.model.Project}
     * @since 1.13
     */
    protected UpdateProject(de.yourtasks.projectendpoint.model.Project content) {
      super(Projectendpoint.this, "PUT", REST_PATH, content, de.yourtasks.projectendpoint.model.Project.class);
    }

    @Override
    public UpdateProject setAlt(java.lang.String alt) {
      return (UpdateProject) super.setAlt(alt);
    }

    @Override
    public UpdateProject setFields(java.lang.String fields) {
      return (UpdateProject) super.setFields(fields);
    }

    @Override
    public UpdateProject setKey(java.lang.String key) {
      return (UpdateProject) super.setKey(key);
    }

    @Override
    public UpdateProject setOauthToken(java.lang.String oauthToken) {
      return (UpdateProject) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateProject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateProject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateProject setQuotaUser(java.lang.String quotaUser) {
      return (UpdateProject) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateProject setUserIp(java.lang.String userIp) {
      return (UpdateProject) super.setUserIp(userIp);
    }

    @Override
    public UpdateProject set(String parameterName, Object value) {
      return (UpdateProject) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Projectendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Projectendpoint}. */
    @Override
    public Projectendpoint build() {
      return new Projectendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ProjectendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setProjectendpointRequestInitializer(
        ProjectendpointRequestInitializer projectendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(projectendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
